// Decompiled with JetBrains decompiler
// Type: XenAPI.Proxy_VIF
// Assembly: XenServer, Version=6.1.0.1, Culture=neutral, PublicKeyToken=102be611e60e8ddc
// MVID: 11619AB1-8160-47E5-8915-DFF772C11F71
// Assembly location: C:\Users\ShawnWang\Desktop\wlb\XenServer.dll

using CookComputing.XmlRpc;

namespace XenAPI
{
  [XmlRpcMissingMapping(MappingAction.Ignore)]
  public class Proxy_VIF
  {
    public string uuid;
    public string[] allowed_operations;
    public object current_operations;
    public string device;
    public string network;
    public string VM;
    public string MAC;
    public string MTU;
    public object other_config;
    public bool currently_attached;
    public string status_code;
    public string status_detail;
    public object runtime_properties;
    public string qos_algorithm_type;
    public object qos_algorithm_params;
    public string[] qos_supported_algorithms;
    public string metrics;
    public bool MAC_autogenerated;
    public string locking_mode;
    public string[] ipv4_allowed;
    public string[] ipv6_allowed;
  }
}
